# Extra autostart processes
# exec-once = uwsm app -- my-service
exec-once = hyprsunset -t 4500
exec-once = mpvpaper HDMI-A-1 -o "no-keepaspect" ~/Imagens/wallpapers/itachi-v.jpg
exec-once = mpvpaper DP-1 -o "--loop --no-audio" ~/Imagens/wallpapers/rick-and-morty-fart.jpg
