# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/autostart.conf

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
general {
    # Gaps and border
    gaps_in = 2
    gaps_out = 2
    gaps_workspaces = 50

    border_size = 1
    col.active_border = rgba(0DB7D4FF)
    col.inactive_border = rgba(31313600)
    resize_on_border = true

    no_focus_fallback = true

    allow_tearing = true # This just allows the `immediate` window rule to work

    snap {
    	enabled = true
    }
}
decoration {
    rounding = 18
    

    blur {
        enabled = true
        special = false
        new_optimizations = true
        size = 14
        passes = 3
        brightness = 1
        noise = 0.01
        contrast = 1
        popups = true
        popups_ignorealpha = 0.6
        input_methods = true
        input_methods_ignorealpha = 0.8
    }

    shadow {
        enabled = true
        ignore_window = true
        range = 30
        offset = 0 2
        render_power = 4
        color = rgba(00000010)
    }

# Dim
    dim_inactive = true
    dim_strength = 0.025
    dim_special = 0.07
}
windowrulev2 = opacity 1, class:^(firefox)
windowrulev2 = opacity 1, class:^(code)

input {
    sensitivity = -0.5  # Valor entre -1.0 (mais lento) e 1.0 (mais rápido)
}
